"""add is_active to departments and update audit_logs staff

Revision ID: 4550cd783ea1
Revises: 
Create Date: 2026-10-07 22:29:46.733620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4550cd783ea1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resource', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('resource_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=500), nullable=True))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('nurses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nurses', schema=None) as batch_op:
        batch_op.drop_column('license_number')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('resource_id')
        batch_op.drop_column('resource')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
